/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_springsjy_HelloWorld */

#ifndef _Included_com_example_springsjy_HelloWorld
#define _Included_com_example_springsjy_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_springsjy_HelloWorld
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_springsjy_HelloWorld_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
